before_install:
  - sudo gem uninstall ffi -a
script: "bundle exec rake forem:dummy_app --trace; bundle exec rspec spec"
env:
  - CI=true DB=sqlite
  - CI=true DB=mysql
  - CI=true DB=postgres
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-19mode
